version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/meowtimes-dev/users
file_exists_behavior: OVERWRITE
permissions:
  - object: /var/www/html/meowtimes-dev/users
    pattern: "**"
    owner: ubuntu
